name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy.yml'

env:
  REGISTRY: ghcr.io

jobs:
  # ========================================================
  # JOB 1 : Build & Push Frontend (Vue.js)
  # ========================================================
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Convertit le nom en minuscules et prépare le tag
      - name: Format frontend image name
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_BASE=${{ env.REGISTRY }}/${REPO_LOWER}-frontend" >> $GITHUB_ENV

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./e-lib-backend
          file: ./e-lib-frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:latest
            ${{ env.IMAGE_BASE }}:${{ github.sha }}

